version: "3.8"
services:
  db:
    image: mysql:8.0  # Using your existing MySQL image
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  php:
    image: php:7.4-apache  # Using your existing PHP image
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
